M48
; DRILL file KiCad 10.0.3 date 2026-08-07T12:01:28
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-07T12:01:28+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,Plated,4,7,Buried
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.100
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T2C0.150
%
G90
G05
T1
X4.68Y3.43
T2
X6.85Y4.88
M30
