M48
; DRILL file KiCad 10.0.3 date 2026-08-07T12:01:28
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-07T12:01:28+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,Plated,3,4,Buried
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.100
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T2C0.150
%
G90
G05
T1
X4.09Y5.2
T2
X1.1Y3.04
X4.03Y4.24
X4.24Y-5.63
M30
