"""Cadence Allegro Third-Party (Telesis-style) netlist writer.

Accepted by Allegro PCB Editor via `File → Import → Logic` (or
`File → Import → Cadence Third-Party Netlist` in newer versions).
Skips Design Capture / OrCAD Capture entirely: parts arrive in Allegro
Layout with refdes + part-type; padstacks (footprints) get assigned
during layout via the Padstack / Symbol Library mapping pass.

If a footprint-inventory CSV with `Allegro_Equivalent` is supplied,
those names are emitted instead of KiCad-derived names — drop-in
import to Allegro without a separate mapping pass.

Telesis format ($PACKAGES line):
  <padstack> ! <device> ! '<part_class>' ; <REFDES>

$NETS line:
  <netname-or-'quoted'> ; <REFDES.PIN> <REFDES.PIN> ...

`!` is a FIELD SEPARATOR inside the package line — not a line prefix.
Quote net names that start with non-letter chars (e.g. '+3.3V').
"""

from __future__ import annotations

from pathlib import Path

from smash.state import Design
from smash.export._common import (
    all_components,
    nets_with_pins,
    net_connections,
    footprint_name,
    footprint_full,
    sanitize_allegro_id,
    allegro_net_name,
)


# Max characters per line; Allegro caps at 1024 (SPMHA2-1) but we stay
# comfortably under it.
_MAX_LINE = 200


def write_allegro_netlist(
    design: Design,
    path: str | Path,
    *,
    footprint_map: dict[str, str] | None = None,
) -> dict:
    """Write a Cadence Allegro Telesis netlist.

    Args:
      design:         the Design to render.
      path:           output filename.
      footprint_map:  optional {KiCad_Footprint: Allegro_Equivalent}
                      mapping. Use `load_allegro_fp_map(csv_path)` to
                      load from a footprint-inventory CSV.

    Returns {n_parts, n_nets}.
    """
    footprint_map = dict(footprint_map or {})

    lines: list[str] = []
    lines.append("; Cadence Allegro Third-Party Netlist -- generated by smash.export.allegro")
    if footprint_map:
        lines.append(f"; Footprint mapping: {len(footprint_map)} entries supplied")
    lines.append("")
    lines.append("$PACKAGES")
    components = all_components(design)
    for c in components:
        ref = str(c.ref)
        manf_pn = (getattr(c, "manf_pn", "") or "").strip()
        value = (getattr(c, "value", "") or "").strip()
        name = (getattr(c, "name", "") or "").strip()
        fp_full = footprint_full(c)
        # Allegro footprint name: prefer mapping; fall back to KiCad-suffix.
        if fp_full in footprint_map:
            footprint = sanitize_allegro_id(footprint_map[fp_full])
        else:
            footprint = sanitize_allegro_id(footprint_name(c))
        part_name = sanitize_allegro_id(manf_pn or value or name or "PART")
        part_class = (value or manf_pn or name or "Part").replace("'", "")
        # Telesis $PACKAGES line: <padstack> ! <device> ! '<class>' ; REFDES
        lines.append(
            f"{footprint} ! {part_name} ! '{part_class}' ; {ref}"
        )

    lines.append("")
    lines.append("$NETS")

    n_nets = 0
    for net in nets_with_pins(design):
        n_nets += 1
        net_name = allegro_net_name(net.name)
        connections = [
            f"{ref}.{num}" for ref, num in net_connections(net)
        ]
        # Telesis $NETS: "<name> ; <pin> <pin> ..." with NO trailing
        # semicolon. Continuation lines signalled by trailing comma.
        cur = f"{net_name} ; "
        for tok in connections:
            if cur.endswith(" "):
                cur += tok
            elif len(cur) + 1 + len(tok) > _MAX_LINE:
                lines.append(cur + ",")
                cur = tok
            else:
                cur += " " + tok
        lines.append(cur)

    lines.append("")
    lines.append("$END")

    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines))
        f.write("\n")

    return {"n_parts": len(components), "n_nets": n_nets}
