"""Parametric hex mesh of a rigid board tile for CalculiX.

Generates a structured C3D8 hex mesh covering the board's circular
outline plus chip body-blocks above F.Cu. The mesh is intentionally
simple (uniform Cartesian xy grid clipped to the circle by centroid
inclusion, configurable Z layering by stackup role) — the FEA's
binding R is the element count, and a 1 mm xy / 3-z-layer mesh on a
Ø 34 tile lands around 3 000 elements, which CalculiX 2.23 solves
statically in seconds.

Element-set tags emitted per mesh:

  BOARD_BULK       — every in-plane element in the FR-4 / Rogers core
  CU_COIN          — elements whose xy centroid sits inside the coin's
                      flange footprint AND whose z range overlaps the
                      coin's Z extent (the coin replaces FR-4 with Cu)
  BCU_SUBSTRATE    — the thin bottom-Cu + dielectric_below layer
  FCU_SUBSTRATE    — the thin top-Cu + Rogers dielectric (radar) or
                      top FR-4 + soldermask (other tiles) layer
  CHIP_<ref>       — one set per chip body-block, used to apply
                      density-based body force from the chip's mass

Node sets emitted:

  ALL_NODES                — every node
  SUPPORT_RING_TOP / BOT   — nodes on the outer cylinder face, top
                              and bottom z extents — where the snake-
                              stack spacer rests. Used by build_deck
                              to fix the snake-stack ring DOFs.
  CHIP_PAD_<ref>           — the bottom nodes of each chip body-block
                              (proxy for solder-pad locations; the
                              report module maps these back to ref).

The result is a `BoardMesh` dataclass the deck builder consumes.
"""
from __future__ import annotations

import dataclasses
import math

import numpy as np

from smash.state import Board


# Default xy element size. 1 mm × 1 mm cells on a Ø 34 tile gives ~900
# in-plane elements; coarser is fine for first-iteration stress envelopes
# but masks <2 mm features (small BGAs). 0.5 mm gives ~3 600 in-plane.
DEFAULT_XY_ELEMENT_MM = 1.0


@dataclasses.dataclass
class MeshElement:
    """One hex element. CCX 1-based node IDs in the standard C3D8
    ordering: bottom face CCW from (-x, -y, -z) then top face CCW
    from (-x, -y, +z)."""
    eid: int                              # 1-based CCX element ID
    nodes: list                            # length-8 list of 1-based node IDs
    centroid_xyz_mm: tuple                 # for material classification


@dataclasses.dataclass
class TieSpec:
    """One *TIE constraint to emit in the deck: a slave node set tied
    to a master node set (both defined in BoardMesh.node_sets).
    Generated by the mesh when underfill blocks need to be glued to
    the board's F.Cu top face (the structured grid doesn't align with
    arbitrary chip positions)."""
    name: str
    slave_nset: str
    master_nset: str


@dataclasses.dataclass
class SpringPairSpec:
    """Phase G — cohesive zone at solder pads. One per (chip, pad-node)
    pair, declaring the compliant solder-joint connection between a
    chip-bottom node and the nearest F.Cu grid node. The deck builder
    calibrates per-direction stiffness from `joint_geometry()`
    (h_joint + family + n_pads), so
    BGAs see SAC305 ball compliance and QFNs/leadless parts get the
    appropriate fillet/lead-bending compliance."""
    chip_ref: str
    pad_node: int                # chip-side node (the SLAVE; UF bottom
                                  # for underfilled chips, chip-block
                                  # bottom otherwise)
    fcu_node: int                # nearest F.Cu top-face node (MASTER)
    family: str | None = None    # joint geometry family — passed to the
                                  # deck builder for stiffness calibration
    n_pads: int = 4              # # of solder pads on this chip
    h_joint_mm: float = 0.25     # solder joint height
    a_pad_total_mm2: float = 0.0  # total joint contact area for the chip
                                   # (sum over all pads); 0 → estimated
                                   # from package family


@dataclasses.dataclass
class BoardMesh:
    """A structured hex mesh of a single rigid board tile, ready for
    `build_deck` to wrap in a CCXDeck."""
    board_name: str
    node_coords: list                      # [(node_id, x_m, y_m, z_m), ...]
    elements: list                          # list[MeshElement]
    element_sets: dict                      # name → list[element_id]
    node_sets: dict                          # name → list[node_id]
    z_layer_records: list                   # [(z_lo_mm, z_hi_mm, role), ...]
    ties: list = dataclasses.field(default_factory=list)   # list[TieSpec]
    spring_pairs: list = dataclasses.field(default_factory=list)
                                              # list[SpringPairSpec]
    note: str | None = None
    # F.Cu top-face node grid for interpolating the board surface
    # displacement at an arbitrary (x, y) — used by the joint-STRAIN
    # verdict so it reads the board displacement AT the pad location
    # rather than at the offset nearest grid node. {"grid": node_id[nx][ny]
    # (0 = outside board), "x0": mm, "y0": mm, "xy": mm}.
    fcu_top: dict | None = None

    @property
    def n_nodes(self) -> int:
        return len(self.node_coords)

    @property
    def n_elements(self) -> int:
        return len(self.elements)

    def elset(self, name: str) -> list:
        return self.element_sets.get(name, [])


# ── helpers ────────────────────────────────────────────────────────────


def _board_radius_mm(board: Board) -> float:
    g = board.geometry
    if g is None or g.diameter_mm is None:
        raise ValueError(
            f"{board.name}: board geometry has no diameter_mm — "
            f"the hex mesher only handles circular tiles for now"
        )
    return g.diameter_mm / 2.0


def _stackup_z_layers(board: Board, *,
                      consolidate: bool = True,
                      n_core_bands: int | None = None) -> list:
    """Reduce the per-layer stackup to a small number of Z element-layers
    suitable for FEA. Each returned tuple is `(z_lo_mm, z_hi_mm, role)`
    where role is one of {"bcu_substrate", "core", "fcu_substrate"}.

    With `consolidate=True` (default), thin Cu foils (~17-35 µm) are
    merged into adjacent dielectric layers — the FEA would otherwise
    need element layers ~30 µm thick, which forces the xy element down
    to ~30 µm too to keep aspect ratios reasonable, blowing up element
    count. Consolidation lumps Cu mass + stiffness into the bulk core,
    which slightly overstates board E (Cu is much stiffer than FR-4)
    but is conservative for stress.

    `n_core_bands` (>1) refines the single consolidated CORE into that
    many equal z-slabs (thin B.Cu / F.Cu substrate roles preserved).
    This is the "improvement A" through-thickness resolution: with only
    one core element the mesh cannot resolve a Cu coin's DEPTH (the coin
    override tests each element's z-centroid, and one centroid = binary
    coin/no-coin), nor the stiffness distribution about the neutral axis.
    Slabs stay homogeneous FR-4 here (foil E is unset ≈ FR-4 in the
    current material model — the per-band effective-modulus step lands
    with improvement D); the refinement is what makes a partial-depth
    coin resolvable.
    """
    stackup = list(board.stackup or [])
    if not stackup:
        raise ValueError(
            f"{board.name}: empty stackup — call `board.set_fitted_stackup()` "
            f"before meshing"
        )
    # Walk top→bottom (stackup is in that order) but report bottom→top.
    total_z_mm = 0.0
    z = 0.0
    layer_zs = []
    # Walk bottom-up. board.stackup is top→bottom so reverse iter.
    for i in range(len(stackup) - 1, -1, -1):
        layer = stackup[i]
        t_cu = layer.thickness_um / 1000.0
        layer_zs.append((z, z + t_cu, layer.name))
        z += t_cu
        if i > 0:
            di = stackup[i - 1].dielectric_below
            if di is not None:
                t_di = di.thickness_um / 1000.0
                layer_zs.append((z, z + t_di, "dielectric"))
                z += t_di
    total_z_mm = z

    if not consolidate:
        return layer_zs

    # Three-layer consolidation: thin bottom-substrate (B.Cu + first
    # dielectric), thick bulk core (everything in between), thin top-
    # substrate (last dielectric + F.Cu).
    if total_z_mm <= 0:
        raise ValueError(f"{board.name}: zero-thickness stackup")
    # Use ~0.10 mm for the thin substrate layers (covers B.Cu/F.Cu +
    # adjacent dielectric) or 5% of total, whichever is larger.
    thin = max(0.10, total_z_mm * 0.05)
    if n_core_bands and n_core_bands > 1:
        core_lo, core_hi = thin, total_z_mm - thin
        dz = (core_hi - core_lo) / n_core_bands
        bands = [(0.0, thin, "bcu_substrate")]
        for i in range(n_core_bands):
            bands.append((core_lo + i * dz, core_lo + (i + 1) * dz, "core"))
        bands.append((total_z_mm - thin, total_z_mm, "fcu_substrate"))
        return bands
    return [
        (0.0,           thin,                  "bcu_substrate"),
        (thin,          total_z_mm - thin,     "core"),
        (total_z_mm - thin, total_z_mm,        "fcu_substrate"),
    ]


def _grid_dims(radius_mm: float, xy_mm: float) -> tuple:
    """`(nx, ny, x0, y0)` for a Cartesian grid that fully covers the
    Ø radius centred at origin. Returns the count of NODES along each
    axis (one more than elements)."""
    n = int(math.ceil(2.0 * radius_mm / xy_mm))
    if n % 2 == 1:
        n += 1                              # even → grid is symmetric
    x0 = -n * xy_mm / 2.0
    y0 = -n * xy_mm / 2.0
    return n + 1, n + 1, x0, y0


def _in_board(xc: float, yc: float, radius_mm: float) -> bool:
    return xc * xc + yc * yc <= radius_mm * radius_mm + 1e-9


def _coin_under_xy(xc_mm: float, yc_mm: float, board: Board) -> object | None:
    """Return the first coin whose flange covers `(xc, yc)`, else None.
    Uses the coin's `covers_position` with zero clearance (point test)."""
    for coin in (board.cu_coin_inserts or []):
        if coin.covers_position(xc_mm, yc_mm, clearance_mm=0.0):
            return coin
    return None


# ── main entry point ──────────────────────────────────────────────────


def _chip_blocks_xyz_aabb(board: Board, z_top_board_mm: float,
                          underfill_thickness_mm: float) -> list:
    """Return [(x_lo, y_lo, x_hi, y_hi, z_lo, z_hi)] AABB in mm for
    every chip placement on the board, including the UF layer below
    when present. Used by the Stycast-fill walker to skip cells whose
    centroid is inside a chip's body (chip block + UF brick already
    occupy that volume in the mesh), while leaving Stycast ABOVE the
    chip available for the chip-top *TIE coupling."""
    from smash.state import Chip
    from smash.state.antenna import Antenna
    from smash.layout.placer.grid import footprint_bbox_mm
    out = []
    for pl in (board.chip_placements or []):
        c = pl.item
        if not isinstance(c, (Chip, Antenna)):
            continue
        fp = getattr(c, "footprint", None)
        if fp is None:
            continue
        lo_x, lo_y, hi_x, hi_y = footprint_bbox_mm(fp)
        w, h = hi_x - lo_x, hi_y - lo_y
        if w <= 0 or h <= 0:
            w, h = getattr(fp, "size_mm", None) or (1.0, 1.0)
        ht = (getattr(fp, "height_mm", None)
              or getattr(c, "height_mm", None) or 0.5)
        if w <= 0 or h <= 0 or ht <= 0:
            continue
        cx, cy = pl.position_mm
        uf = (underfill_thickness_mm
              if getattr(c, "underfill", None) else 0.0)
        z_lo = z_top_board_mm
        z_hi = z_top_board_mm + uf + ht
        out.append((cx - w / 2.0, cy - h / 2.0,
                    cx + w / 2.0, cy + h / 2.0,
                    z_lo, z_hi))
    return out


# Kept for compatibility with Phase B's tests + the report module.
def _chip_blocks_xy_footprint(board: Board) -> list:
    """xy-only AABBs (drops z). Calling sites that don't have the
    UF thickness handy still want a quick xy filter."""
    from smash.state import Chip
    from smash.state.antenna import Antenna
    from smash.layout.placer.grid import footprint_bbox_mm
    out = []
    for pl in (board.chip_placements or []):
        c = pl.item
        if not isinstance(c, (Chip, Antenna)):
            continue
        fp = getattr(c, "footprint", None)
        if fp is None:
            continue
        lo_x, lo_y, hi_x, hi_y = footprint_bbox_mm(fp)
        w, h = hi_x - lo_x, hi_y - lo_y
        if w <= 0 or h <= 0:
            w, h = getattr(fp, "size_mm", None) or (1.0, 1.0)
        cx, cy = pl.position_mm
        out.append((cx - w / 2.0, cy - h / 2.0,
                    cx + w / 2.0, cy + h / 2.0))
    return out


def _xy_in_chip(x_mm: float, y_mm: float, chip_aabbs: list) -> bool:
    for entry in chip_aabbs:
        lo_x, lo_y, hi_x, hi_y = entry[:4]
        if lo_x - 1e-9 <= x_mm <= hi_x + 1e-9 \
                and lo_y - 1e-9 <= y_mm <= hi_y + 1e-9:
            return True
    return False


def _xyz_in_chip_body(x_mm: float, y_mm: float, z_mm: float,
                      chip_aabbs_xyz: list) -> bool:
    """True iff the point is inside any chip body AABB (including UF
    below). Used by the Stycast walker to skip cells whose centroid
    sits inside a chip's actual occupied volume — distinct from the
    xy-only test which would also blank Stycast above tall chips."""
    for (lo_x, lo_y, hi_x, hi_y, lo_z, hi_z) in chip_aabbs_xyz:
        if lo_x - 1e-9 <= x_mm <= hi_x + 1e-9 \
                and lo_y - 1e-9 <= y_mm <= hi_y + 1e-9 \
                and lo_z - 1e-9 <= z_mm <= hi_z + 1e-9:
            return True
    return False


def _max_chip_top_z_mm(board: Board, z_top_board_mm: float,
                       underfill_thickness_mm: float) -> float:
    """Maximum z reached by any chip's top face. Returns
    `z_top_board_mm` when the board has no chips (degenerate — Stycast
    walker will emit nothing)."""
    z_max = z_top_board_mm
    from smash.state import Chip
    from smash.state.antenna import Antenna
    for pl in (board.chip_placements or []):
        c = pl.item
        if not isinstance(c, (Chip, Antenna)):
            continue
        fp = getattr(c, "footprint", None)
        if fp is None:
            continue
        ht = (getattr(fp, "height_mm", None)
              or getattr(c, "height_mm", None) or 0.5)
        if ht <= 0:
            continue
        uf = (underfill_thickness_mm
              if getattr(c, "underfill", None) else 0.0)
        z_top = z_top_board_mm + uf + ht
        if z_top > z_max:
            z_max = z_top
    return z_max


def build_board_mesh(board: Board, *,
                     xy_element_mm: float = DEFAULT_XY_ELEMENT_MM,
                     include_chip_blocks: bool = False,
                     include_potting: bool = False,
                     potting_z_layers: int = 2,
                     potting_top_margin_mm: float = 0.5,
                     n_core_bands: int | None = None,
                     ) -> BoardMesh:
    """Generate a structured hex mesh of one rigid board.

    Args:
      board:             Board with populated `stackup`, `chip_placements`,
                         and optionally `cu_coin_inserts`.
      xy_element_mm:     in-plane element edge length. 1 mm → ~900
                         elements on a Ø 34 tile.
      include_chip_blocks: when True, emit one hex element per chip
                         placement above F.Cu, in element-set CHIP_<ref>.
                         For chips with `chip.underfill` set (a name into
                         FabProfile.adhesives), an Eccobond underfill
                         layer is also emitted directly under the chip
                         block, with shared nodes (chip bottom face =
                         underfill top face). The underfill's BOTTOM
                         face is `*TIE`-bound to the board's F.Cu
                         surface so chip + underfill are properly
                         coupled to the board even where the structured
                         grid doesn't align with the chip's xy. Chips
                         WITHOUT underfill get *TIE coupling directly
                         from the chip-block bottom to the F.Cu
                         (no UF layer in between).
      include_potting:   when True, fill the volume above F.Cu (excluding
                         chip + underfill volumes) with Stycast 2651MM
                         encapsulant hex elements. The fill nodes
                         coincide with the board's F.Cu nodes at
                         z=z_top_board, so the bottom face of the
                         potting block is directly bonded to F.Cu via
                         shared nodes (no *TIE needed at the F.Cu
                         interface). Above F.Cu the potting extends
                         to `max(chip_top) + potting_top_margin_mm`
                         and discretises into `potting_z_layers` even
                         z-slices.
      potting_z_layers:  number of z-element slices in the Stycast block.
                         2 is a reasonable first-iteration default;
                         more captures the through-thickness stress
                         gradient at the cost of more elements.
      potting_top_margin_mm: extra Stycast thickness above the tallest
                         chip — represents the gap to the spacer above.

    Returns a `BoardMesh` with `node_coords`, `elements`, element_sets,
    node_sets keyed by name.
    """
    if board.kind != "rigid":
        raise ValueError(f"{board.name}: hex mesh only for rigid tiles "
                         f"(kind={board.kind!r})")

    radius_mm = _board_radius_mm(board)
    z_layers = _stackup_z_layers(board, n_core_bands=n_core_bands)

    # ── nodes: 3D grid over the bounding box × stackup z-layers ─────
    nx, ny, x0, y0 = _grid_dims(radius_mm, xy_element_mm)
    nz_breakpoints = sorted({0.0, *[z_lo for z_lo, _, _ in z_layers],
                              *[z_hi for _, z_hi, _ in z_layers]})
    nz = len(nz_breakpoints)

    # node_grid[ix][iy][iz] = 1-based node id, or 0 if outside board.
    node_grid = [[[0] * nz for _ in range(ny)] for _ in range(nx)]
    node_coords = []
    next_node_id = 1

    for ix in range(nx):
        x_mm = x0 + ix * xy_element_mm
        for iy in range(ny):
            y_mm = y0 + iy * xy_element_mm
            # Node lives inside the board if its xy lies on or inside
            # the disc — we test the node, not the cell, so cells with
            # any node inside still get their corners. Cells whose
            # CENTROID is outside the disc are skipped at element time.
            if x_mm * x_mm + y_mm * y_mm > (radius_mm + xy_element_mm) ** 2:
                continue
            for iz, z_mm in enumerate(nz_breakpoints):
                node_grid[ix][iy][iz] = next_node_id
                node_coords.append((next_node_id,
                                    x_mm * 1e-3, y_mm * 1e-3, z_mm * 1e-3))
                next_node_id += 1

    # ── elements: one C3D8 per (ix, iy, iz) cell whose CENTROID is
    #    inside the disc and whose 8 corner nodes all exist. ────────
    elements = []
    elset: dict = {
        "BOARD_BULK": [],
        "CU_COIN": [],
        "BCU_SUBSTRATE": [],
        "FCU_SUBSTRATE": [],
    }
    z_layer_z_lookup = []
    for z_lo, z_hi, role in z_layers:
        z_layer_z_lookup.append((z_lo, z_hi, role))

    next_eid = 1
    for ix in range(nx - 1):
        x_lo = x0 + ix * xy_element_mm
        x_hi = x_lo + xy_element_mm
        x_cent = 0.5 * (x_lo + x_hi)
        for iy in range(ny - 1):
            y_lo = y0 + iy * xy_element_mm
            y_hi = y_lo + xy_element_mm
            y_cent = 0.5 * (y_lo + y_hi)
            if not _in_board(x_cent, y_cent, radius_mm):
                continue
            coin = _coin_under_xy(x_cent, y_cent, board)

            for iz in range(nz - 1):
                # Resolve the role of the z-layer this element sits in.
                z_lo = nz_breakpoints[iz]
                z_hi = nz_breakpoints[iz + 1]
                z_cent = 0.5 * (z_lo + z_hi)
                role = "core"
                for zr_lo, zr_hi, zr_role in z_layer_z_lookup:
                    if z_cent >= zr_lo - 1e-9 and z_cent <= zr_hi + 1e-9:
                        role = zr_role
                        break

                # Resolve all 8 corner nodes; skip elements where any
                # corner is outside the board (centroid-inclusion can
                # generate cells with a corner outside the disc).
                try:
                    n1 = node_grid[ix][iy][iz]
                    n2 = node_grid[ix + 1][iy][iz]
                    n3 = node_grid[ix + 1][iy + 1][iz]
                    n4 = node_grid[ix][iy + 1][iz]
                    n5 = node_grid[ix][iy][iz + 1]
                    n6 = node_grid[ix + 1][iy][iz + 1]
                    n7 = node_grid[ix + 1][iy + 1][iz + 1]
                    n8 = node_grid[ix][iy + 1][iz + 1]
                except IndexError:
                    continue
                if 0 in (n1, n2, n3, n4, n5, n6, n7, n8):
                    continue

                elem = MeshElement(
                    eid=next_eid,
                    nodes=[n1, n2, n3, n4, n5, n6, n7, n8],
                    centroid_xyz_mm=(x_cent, y_cent, z_cent),
                )
                elements.append(elem)
                next_eid += 1

                # Material classification: coin overrides core inside its
                # Z range; substrate roles get their own set.
                in_coin = (coin is not None
                           and coin.z_bottom_mm - 1e-6 <= z_cent <= coin.z_top_mm + 1e-6)
                if in_coin:
                    elset["CU_COIN"].append(elem.eid)
                elif role == "bcu_substrate":
                    elset["BCU_SUBSTRATE"].append(elem.eid)
                elif role == "fcu_substrate":
                    elset["FCU_SUBSTRATE"].append(elem.eid)
                else:
                    elset["BOARD_BULK"].append(elem.eid)

    # ── Al backing below B.Cu ─────────────────────────────────────
    # If `Board.al_backing_mm > 0` (camera_module today) we add an Al
    # 6061-T6 hex layer below z=0 that shares its TOP face with B.Cu.
    # The spacer-contact surface shifts to the Al's outer bottom ring,
    # so the SUPPORT_RING_BOT node set will track that instead of z=0.
    nset: dict = {}
    al_backing_mm = float(getattr(board, "al_backing_mm", 0.0) or 0.0)
    al_top_z_in_board_frame = 0.0      # z=0 in our current frame
    if al_backing_mm > 0:
        _add_al_backing_below(
            board, elements, elset, node_coords,
            node_grid_xy=node_grid, nx=nx, ny=ny, x0=x0, y0=y0,
            xy_mm=xy_element_mm, radius_mm=radius_mm,
            al_thickness_mm=al_backing_mm,
            iz_bcu_bottom=0,                 # B.Cu bottom = z=0 in board frame
            next_eid_ref=[next_eid],
            next_node_id_ref=[next_node_id],
        )
        # _add_al_backing_below mutates these refs:
        next_eid, next_node_id = (elements[-1].eid + 1,
                                   node_coords[-1][0] + 1)
        # The helper stashes the Al's outer-bottom ring node IDs under
        # a private elset key; pop them into the node set dict.
        ring = elset.pop("__AL_RING_NODES__", [])
        if ring:
            nset["AL_BACKING_BOTTOM_RING"] = ring
        # Stash the Al backing's bottom Z so SUPPORT_RING_BOT can find it.
        al_top_z_in_board_frame = -al_backing_mm
    nset["ALL_NODES"] = list(range(1, next_node_id))

    # ── chip body + per-chip underfill above F.Cu ──────────────────
    ties: list = []
    z_top_board = nz_breakpoints[-1]
    # F.Cu top node set — the master surface every chip-or-underfill
    # column ties down to. Includes every node whose z is at the
    # board's top face AND xy is inside the disc.
    nset["FCU_TOP"] = [
        nid for (nid, xm, ym, zm) in node_coords
        if abs(zm * 1000.0 - z_top_board) < 1e-6
    ]
    next_eid_ref = [next_eid]
    next_node_id_ref = [next_node_id]
    spring_pairs: list = []
    if include_chip_blocks:
        _add_chip_blocks_with_underfill(
            board, elements, elset, nset, node_coords, ties,
            spring_pairs,
            next_eid_ref=next_eid_ref,
            next_node_id_ref=next_node_id_ref,
            z_top_board_mm=z_top_board,
            fcu_top_nset=nset["FCU_TOP"],
            node_coords_for_lookup=node_coords,
        )

    # ── Stycast 2651MM potting fill above F.Cu ────────────────────
    # Reuse the SAME structured xy grid we already built for the board,
    # so the potting block's bottom-face nodes ARE the F.Cu top-face
    # nodes (shared-node bonding, no extra *TIE needed). Above F.Cu we
    # extrude a fresh column of nodes per z-layer, with cells whose xy
    # centroid sits inside any chip footprint SKIPPED (chip body /
    # underfill bricks already occupy that volume).
    if include_potting:
        z_pot_top = (_max_chip_top_z_mm(board, z_top_board,
                                          UNDERFILL_THICKNESS_MM_DEFAULT)
                     + potting_top_margin_mm)
        if z_pot_top > z_top_board + 1e-6:
            _add_stycast_potting(
                board, elements, elset, nset, node_coords,
                node_grid_xy=node_grid, nx=nx, ny=ny, x0=x0, y0=y0,
                xy_mm=xy_element_mm, radius_mm=radius_mm,
                z_bottom_mm=z_top_board,
                z_top_mm=z_pot_top,
                n_z_layers=potting_z_layers,
                next_eid_ref=next_eid_ref,
                next_node_id_ref=next_node_id_ref,
                iz_fcu_top=nz - 1,
            )

    # ── boundary node sets: the snake-stack support ring ────────────
    # Top and bottom OUTER ring of nodes (radius ≈ board radius); these
    # are where the spacer above/below rests. CCX clamps a BC to a node
    # set, not a face — using ring nodes approximates the spacer's
    # support reaction. If an Al backing is present, the bottom ring
    # shifts down to the Al's bottom face (the spacer below rests on
    # the Al, not on B.Cu).
    if al_backing_mm > 0:
        # Outer ring at z = -al_backing_mm (Al backing bottom). The Al
        # nodes were appended sequentially and tagged in the
        # `AL_BACKING_BOTTOM_RING` node set by the helper.
        nset["SUPPORT_RING_BOT"] = nset.get("AL_BACKING_BOTTOM_RING") or []
    else:
        nset["SUPPORT_RING_BOT"] = _outer_ring_node_set(
            node_grid, nx, ny, iz=0,
            x0=x0, y0=y0, xy_mm=xy_element_mm, radius_mm=radius_mm,
        )
    nset["SUPPORT_RING_TOP"] = _outer_ring_node_set(node_grid, nx, ny,
                                                     iz=nz - 1,
                                                     x0=x0, y0=y0,
                                                     xy_mm=xy_element_mm,
                                                     radius_mm=radius_mm)

    fcu_top = {
        "grid": [[node_grid[ix][iy][nz - 1] for iy in range(ny)]
                 for ix in range(nx)],
        "x0": x0, "y0": y0, "xy": xy_element_mm,
    }

    return BoardMesh(
        board_name=board.name,
        node_coords=node_coords,
        elements=elements,
        element_sets=elset,
        node_sets=nset,
        z_layer_records=z_layers,
        ties=ties,
        spring_pairs=spring_pairs,
        note=(f"hex mesh: {len(node_coords)} nodes, "
              f"{len(elements)} elements; "
              f"xy={xy_element_mm} mm, {len(z_layers)} z-layers"),
        fcu_top=fcu_top,
    )


def _outer_ring_node_set(node_grid, nx, ny, *, iz, x0, y0, xy_mm,
                          radius_mm) -> list:
    """Nodes within `xy_mm` of the board's outer radius at z=z_at[iz]."""
    out = []
    r_outer = radius_mm
    r_inner = max(0.0, radius_mm - xy_mm * 1.5)
    for ix in range(nx):
        x_mm = x0 + ix * xy_mm
        for iy in range(ny):
            y_mm = y0 + iy * xy_mm
            r = math.sqrt(x_mm * x_mm + y_mm * y_mm)
            if r_inner <= r <= r_outer + 1e-9:
                nid = node_grid[ix][iy][iz]
                if nid > 0:
                    out.append(nid)
    return out


def _add_al_backing_below(
        board, elements, elset, node_coords, *,
        node_grid_xy, nx, ny, x0, y0, xy_mm, radius_mm,
        al_thickness_mm: float, iz_bcu_bottom: int,
        next_eid_ref, next_node_id_ref,
) -> None:
    """Emit an Al 6061-T6 hex layer BELOW the board, extending from
    z = -al_thickness_mm to z = 0. The TOP face shares B.Cu's bottom
    nodes (`node_grid_xy[ix][iy][iz_bcu_bottom]`), so the Al is bonded
    to the PCB without an explicit *TIE — the bond adhesive (thermal
    interface pad) is treated as rigid for first-iteration FEA.

    Mutates `elements`, `elset`, `node_coords`; populates element set
    AL_BACKING and node set AL_BACKING_BOTTOM_RING (the outer ring at
    z = -al_thickness_mm, used by the deck builder to pin the spacer
    support reaction)."""
    # New node layer at z = -al_thickness_mm; the top layer is the
    # existing B.Cu bottom (shared nodes).
    al_z_node = [[0 for _ in range(ny)] for _ in range(nx)]
    for ix in range(nx):
        x_mm = x0 + ix * xy_mm
        for iy in range(ny):
            y_mm = y0 + iy * xy_mm
            if node_grid_xy[ix][iy][iz_bcu_bottom] == 0:
                continue
            nid = next_node_id_ref[0]
            node_coords.append(
                (nid, x_mm * 1e-3, y_mm * 1e-3,
                 -al_thickness_mm * 1e-3)
            )
            al_z_node[ix][iy] = nid
            next_node_id_ref[0] = nid + 1

    elset.setdefault("AL_BACKING", [])
    bot_ring = []
    for ix in range(nx - 1):
        x_lo = x0 + ix * xy_mm
        x_hi = x_lo + xy_mm
        x_cent = 0.5 * (x_lo + x_hi)
        for iy in range(ny - 1):
            y_lo = y0 + iy * xy_mm
            y_hi = y_lo + xy_mm
            y_cent = 0.5 * (y_lo + y_hi)
            if not _in_board(x_cent, y_cent, radius_mm):
                continue
            try:
                # Bottom 4 = new Al nodes at z=-al_thickness_mm
                n1 = al_z_node[ix][iy]
                n2 = al_z_node[ix + 1][iy]
                n3 = al_z_node[ix + 1][iy + 1]
                n4 = al_z_node[ix][iy + 1]
                # Top 4 = existing B.Cu bottom nodes at z=0
                n5 = node_grid_xy[ix][iy][iz_bcu_bottom]
                n6 = node_grid_xy[ix + 1][iy][iz_bcu_bottom]
                n7 = node_grid_xy[ix + 1][iy + 1][iz_bcu_bottom]
                n8 = node_grid_xy[ix][iy + 1][iz_bcu_bottom]
            except IndexError:
                continue
            if 0 in (n1, n2, n3, n4, n5, n6, n7, n8):
                continue
            eid = next_eid_ref[0]
            elements.append(MeshElement(
                eid=eid, nodes=[n1, n2, n3, n4, n5, n6, n7, n8],
                centroid_xyz_mm=(x_cent, y_cent, -al_thickness_mm / 2.0),
            ))
            elset["AL_BACKING"].append(eid)
            next_eid_ref[0] = eid + 1

    # Build the AL_BACKING_BOTTOM_RING node set: outer-ring nodes on
    # the Al's bottom face. Reuses the radial-ring filter the existing
    # helper uses for the board's outer rings.
    r_outer = radius_mm
    r_inner = max(0.0, radius_mm - xy_mm * 1.5)
    for ix in range(nx):
        x_mm = x0 + ix * xy_mm
        for iy in range(ny):
            y_mm = y0 + iy * xy_mm
            r = math.sqrt(x_mm * x_mm + y_mm * y_mm)
            if r_inner <= r <= r_outer + 1e-9 and al_z_node[ix][iy]:
                bot_ring.append(al_z_node[ix][iy])
    # Stash via nset directly — caller may not have built nset yet,
    # so we route through elset['__AL_RING__'] which the caller pops.
    elset.setdefault("__AL_RING_NODES__", bot_ring)


def _add_stycast_potting(
        board, elements, elset, nset, node_coords, *,
        node_grid_xy, nx, ny, x0, y0, xy_mm, radius_mm,
        z_bottom_mm, z_top_mm, n_z_layers,
        next_eid_ref, next_node_id_ref, iz_fcu_top,
) -> None:
    """Fill the volume above F.Cu with Stycast 2651MM hex elements,
    skipping cells whose xyz centroid sits inside any chip body (chip
    block + UF brick volume). Stycast ABOVE a chip is retained so the
    chip-top *TIE coupling has a Stycast face to project onto.

    The bottom-face nodes ARE the F.Cu top-face nodes from the board
    mesh (shared via `node_grid_xy`), so the potting is automatically
    bonded to the board without an explicit *TIE. Above the F.Cu we
    extrude a fresh column of nodes per z-layer.

    Element set STYCAST_FILL receives every emitted element; the deck
    builder binds it to the Stycast 2651MM material card.
    """
    # Use the 3D AABB so Stycast ABOVE chips remains (only cells inside
    # the chip body volume are skipped). This makes the chip-top *TIE
    # coupling possible — there's Stycast for the chip top to attach to.
    chip_aabbs = _chip_blocks_xyz_aabb(
        board, z_top_board_mm=z_bottom_mm,
        underfill_thickness_mm=UNDERFILL_THICKNESS_MM_DEFAULT,
    )

    # Generate the in-between Z node layers, all the way to z_top_mm.
    n_extra = n_z_layers   # we already share the iz=iz_fcu_top layer
    dz = (z_top_mm - z_bottom_mm) / n_z_layers

    # Build a parallel node grid for the potting layers above F.Cu.
    # Layer 0 (the bottom) uses the existing F.Cu nodes from
    # node_grid_xy[ix][iy][iz_fcu_top]; layers 1..n_z_layers get new IDs.
    potting_z_node = [[[0] * (n_extra + 1)
                       for _ in range(ny)] for _ in range(nx)]
    for ix in range(nx):
        x_mm = x0 + ix * xy_mm
        for iy in range(ny):
            y_mm = y0 + iy * xy_mm
            # Bottom row reuses F.Cu nodes (shared-node bonding).
            potting_z_node[ix][iy][0] = node_grid_xy[ix][iy][iz_fcu_top]
            # Skip extra layers when the F.Cu node is outside the board.
            if potting_z_node[ix][iy][0] == 0:
                continue
            for kz in range(1, n_extra + 1):
                nid = next_node_id_ref[0]
                z_mm = z_bottom_mm + kz * dz
                node_coords.append(
                    (nid, x_mm * 1e-3, y_mm * 1e-3, z_mm * 1e-3)
                )
                potting_z_node[ix][iy][kz] = nid
                next_node_id_ref[0] = nid + 1

    elset.setdefault("STYCAST_FILL", [])

    for ix in range(nx - 1):
        x_lo = x0 + ix * xy_mm
        x_hi = x_lo + xy_mm
        x_cent = 0.5 * (x_lo + x_hi)
        for iy in range(ny - 1):
            y_lo = y0 + iy * xy_mm
            y_hi = y_lo + xy_mm
            y_cent = 0.5 * (y_lo + y_hi)
            if not _in_board(x_cent, y_cent, radius_mm):
                continue
            for kz in range(n_z_layers):
                z_cent = z_bottom_mm + (kz + 0.5) * dz
                if _xyz_in_chip_body(x_cent, y_cent, z_cent,
                                      chip_aabbs):
                    continue
                try:
                    n1 = potting_z_node[ix][iy][kz]
                    n2 = potting_z_node[ix + 1][iy][kz]
                    n3 = potting_z_node[ix + 1][iy + 1][kz]
                    n4 = potting_z_node[ix][iy + 1][kz]
                    n5 = potting_z_node[ix][iy][kz + 1]
                    n6 = potting_z_node[ix + 1][iy][kz + 1]
                    n7 = potting_z_node[ix + 1][iy + 1][kz + 1]
                    n8 = potting_z_node[ix][iy + 1][kz + 1]
                except IndexError:
                    continue
                if 0 in (n1, n2, n3, n4, n5, n6, n7, n8):
                    continue
                eid = next_eid_ref[0]
                z_cent = z_bottom_mm + (kz + 0.5) * dz
                elements.append(MeshElement(
                    eid=eid, nodes=[n1, n2, n3, n4, n5, n6, n7, n8],
                    centroid_xyz_mm=(x_cent, y_cent, z_cent),
                ))
                elset["STYCAST_FILL"].append(eid)
                next_eid_ref[0] = eid + 1


UNDERFILL_THICKNESS_MM_DEFAULT = 0.4
"""Effective Eccobond UF1173 capillary thickness between BGA / CSP chip
body and the board's F.Cu top — derived from the typical SAC305 ball
collapse height (~0.25-0.5 mm depending on pitch). This is the same
constant the thermal sim's `r_underfill` uses; lumping it here ties
the FEA's joint compliance to the thermal model's path length."""


def _nearest_fcu_node(x_mm: float, y_mm: float, fcu_top_nset: list,
                       node_coords_for_lookup: list) -> int:
    """Find the F.Cu top-face node closest in xy to (x_mm, y_mm). Used
    to pair each chip-pad node with its compliant-spring partner."""
    # Index node coords by id; only those in fcu_top_nset are candidates.
    coords_by_id = {nid: (xm, ym) for (nid, xm, ym, _zm)
                     in node_coords_for_lookup}
    best_id = None
    best_d2 = float("inf")
    tx, ty = x_mm * 1e-3, y_mm * 1e-3
    for nid in fcu_top_nset:
        coord = coords_by_id.get(nid)
        if coord is None:
            continue
        dx = coord[0] - tx
        dy = coord[1] - ty
        d2 = dx * dx + dy * dy
        if d2 < best_d2:
            best_d2 = d2
            best_id = nid
    return best_id or fcu_top_nset[0]


def _add_chip_blocks_with_underfill(
        board, elements, elset, nset, node_coords, ties, spring_pairs, *,
        next_eid_ref, next_node_id_ref, z_top_board_mm,
        fcu_top_nset, node_coords_for_lookup,
        underfill_thickness_mm: float = UNDERFILL_THICKNESS_MM_DEFAULT,
) -> None:
    """Append per-chip element columns: an Eccobond underfill brick
    sitting on F.Cu, with the chip body brick directly above it
    sharing the underfill's top face. Chips with `Chip.underfill ==
    None` get a "fake" zero-thickness underfill column collapsed into
    a *TIE only — the chip bottom is tied directly to F.Cu.

    Each column emits:
      - element set UF_<ref> (underfill brick, only when chip is
        underfilled) bound to material UNDERFILL in build_deck.
      - element set CHIP_<ref> bound to material CHIP_BODY.
      - node set CHIP_PAD_<ref>: bottom 4 nodes of the BOTTOM brick
        (underfill bottom if present, else chip-block bottom). These
        are the "solder-pad proxy" nodes — the report module pulls
        peak stress from this set per chip.
      - a TieSpec gluing the column's bottom node set to FCU_TOP
        (the structured-grid F.Cu node set) so the column is properly
        coupled to the board.
    """
    from smash.state import Chip
    from smash.state.antenna import Antenna
    from smash.layout.placer.grid import footprint_bbox_mm

    for pl in (board.chip_placements or []):
        c = pl.item
        if not isinstance(c, (Chip, Antenna)):
            continue
        fp = getattr(c, "footprint", None)
        if fp is None:
            continue
        lo_x, lo_y, hi_x, hi_y = footprint_bbox_mm(fp)
        w, h = hi_x - lo_x, hi_y - lo_y
        if w <= 0 or h <= 0:
            w, h = getattr(fp, "size_mm", None) or (1.0, 1.0)
        ht = (getattr(fp, "height_mm", None)
              or getattr(c, "height_mm", None) or 0.5)
        if w <= 0 or h <= 0 or ht <= 0:
            continue
        cx, cy = pl.position_mm

        has_underfill = bool(getattr(c, "underfill", None))
        uf_t = underfill_thickness_mm if has_underfill else 0.0
        z_chip_bot = z_top_board_mm + uf_t
        z_chip_top = z_chip_bot + ht

        x_lo, x_hi = cx - w / 2.0, cx + w / 2.0
        y_lo, y_hi = cy - h / 2.0, cy + h / 2.0

        # ── nodes ─────────────────────────────────────────────────────
        # The column shares 4 nodes between underfill top and chip
        # bottom (when underfill exists). 8 unique nodes per brick;
        # the shared face avoids duplicates.
        nid_base = next_node_id_ref[0]
        if has_underfill:
            # 12 nodes total: 4 at bottom (z=board_top), 4 shared
            # (z=chip_bot = uf_top), 4 at top (z=chip_top).
            col_nodes = [
                (nid_base + 0, x_lo, y_lo, z_top_board_mm),
                (nid_base + 1, x_hi, y_lo, z_top_board_mm),
                (nid_base + 2, x_hi, y_hi, z_top_board_mm),
                (nid_base + 3, x_lo, y_hi, z_top_board_mm),
                (nid_base + 4, x_lo, y_lo, z_chip_bot),
                (nid_base + 5, x_hi, y_lo, z_chip_bot),
                (nid_base + 6, x_hi, y_hi, z_chip_bot),
                (nid_base + 7, x_lo, y_hi, z_chip_bot),
                (nid_base + 8, x_lo, y_lo, z_chip_top),
                (nid_base + 9, x_hi, y_lo, z_chip_top),
                (nid_base + 10, x_hi, y_hi, z_chip_top),
                (nid_base + 11, x_lo, y_hi, z_chip_top),
            ]
            n_col_nodes = 12
            uf_corner_ids = [nid_base + i for i in (0, 1, 2, 3, 4, 5, 6, 7)]
            chip_corner_ids = [nid_base + i for i in (4, 5, 6, 7, 8, 9, 10, 11)]
            pad_proxy_ids = uf_corner_ids[:4]   # bottom 4 = underfill bottom
        else:
            # 8 nodes: chip block only, sitting directly on F.Cu.
            col_nodes = [
                (nid_base + 0, x_lo, y_lo, z_top_board_mm),
                (nid_base + 1, x_hi, y_lo, z_top_board_mm),
                (nid_base + 2, x_hi, y_hi, z_top_board_mm),
                (nid_base + 3, x_lo, y_hi, z_top_board_mm),
                (nid_base + 4, x_lo, y_lo, z_chip_top),
                (nid_base + 5, x_hi, y_lo, z_chip_top),
                (nid_base + 6, x_hi, y_hi, z_chip_top),
                (nid_base + 7, x_lo, y_hi, z_chip_top),
            ]
            n_col_nodes = 8
            uf_corner_ids = None
            chip_corner_ids = [nid_base + i for i in (0, 1, 2, 3, 4, 5, 6, 7)]
            pad_proxy_ids = chip_corner_ids[:4]

        # Convert mm coords to metres on the way in.
        node_coords.extend(
            (nid, xm * 1e-3, ym * 1e-3, zm * 1e-3)
            for (nid, xm, ym, zm) in col_nodes
        )
        next_node_id_ref[0] = nid_base + n_col_nodes

        # ── elements ──────────────────────────────────────────────────
        ref = c.ref
        if has_underfill:
            uf_eid = next_eid_ref[0]
            elements.append(MeshElement(
                eid=uf_eid, nodes=uf_corner_ids,
                centroid_xyz_mm=(cx, cy,
                                  0.5 * (z_top_board_mm + z_chip_bot)),
            ))
            elset[f"UF_{ref}"] = [uf_eid]
            next_eid_ref[0] = uf_eid + 1

        chip_eid = next_eid_ref[0]
        elements.append(MeshElement(
            eid=chip_eid, nodes=chip_corner_ids,
            centroid_xyz_mm=(cx, cy, 0.5 * (z_chip_bot + z_chip_top)),
        ))
        elset[f"CHIP_{ref}"] = [chip_eid]
        next_eid_ref[0] = chip_eid + 1

        # ── node sets + Phase G: cohesive springs + Stycast TIEs ─────
        nset[f"CHIP_PAD_{ref}"] = pad_proxy_ids
        # Phase G: replace the rigid chip-bottom *TIE to F.Cu with
        # discrete *SPRING2 elements representing the actual SAC305
        # ball compliance. For each of the 4 pad-proxy nodes, find
        # the nearest F.Cu top-face node and emit a SpringPairSpec
        # that the deck builder turns into 3 spring elements
        # (X / Y / Z DOFs). Per-direction stiffness comes from the
        # chip's joint geometry via `joint_geometry()`.
        from smash.sim.fea.joint_geometry import joint_geometry
        fp = getattr(c, "footprint", None)
        geom = joint_geometry(fp, name_hint=getattr(fp, "name", ""))
        h_joint_mm = geom.h_joint_mm if geom else 0.25
        family = geom.family if geom else None
        n_pads_chip = len(getattr(fp, "pads", None) or [1])
        # Total joint contact area — estimate from family + pitch.
        a_pad_total = _estimate_joint_area_mm2(fp, n_pads_chip, family)

        # Move the pad-proxy node z DOWN to z_top_board (it already
        # lives there per the column construction). Iterate the 4
        # corners, build a unique node set per spring pair, and emit
        # one SpringPairSpec each.
        for k, pad_nid in enumerate(pad_proxy_ids):
            # Find the pad-node xy position from node_coords (the
            # last entry for each id is the canonical one we stored).
            x_coord = y_coord = 0.0
            for (nid, xm, ym, _zm) in node_coords:
                if nid == pad_nid:
                    x_coord, y_coord = xm * 1000.0, ym * 1000.0
                    break
            fcu_nid = _nearest_fcu_node(
                x_coord, y_coord, fcu_top_nset, node_coords_for_lookup,
            )
            spring_pairs.append(SpringPairSpec(
                chip_ref=ref,
                pad_node=pad_nid,
                fcu_node=fcu_nid,
                family=family,
                n_pads=max(4, n_pads_chip),       # spring per corner
                h_joint_mm=h_joint_mm,
                a_pad_total_mm2=a_pad_total,
            ))

        # Phase G upper half: the encapsulant holds the chip body so
        # shear relief shows up in the FEA. Chip-top and chip-side
        # nodes tie to the Stycast element surface. The chip-bottom
        # rigid *TIE is gone (replaced by springs above), so
        # over-constraint isn't an issue any more.
        chip_top_ids = chip_corner_ids[4:]
        nset[f"CHIP_TOP_{ref}"] = chip_top_ids
        ties.append(TieSpec(
            name=f"TIE_{ref}_TOP_to_STYCAST",
            slave_nset=f"CHIP_TOP_{ref}",
            master_nset="STYCAST_FILL_FACES",
        ))
        # Chip side nodes: all 8 chip-block nodes (4 top + 4 bottom
        # of the chip block — NOT the pad-proxy nodes at UF bottom).
        # These all sit on the chip body's side or top faces and tie
        # to whichever Stycast face is closest.
        chip_side_ids = chip_corner_ids   # all 8 (4 bot + 4 top of chip)
        nset[f"CHIP_SIDES_{ref}"] = chip_side_ids
        ties.append(TieSpec(
            name=f"TIE_{ref}_SIDES_to_STYCAST",
            slave_nset=f"CHIP_SIDES_{ref}",
            master_nset="STYCAST_FILL_FACES",
        ))


def _estimate_joint_area_mm2(footprint, n_pads: int,
                              family: str | None) -> float:
    """Aggregate solder-joint contact area for one chip. For BGAs:
    π·r_ball² · n_pads (r_ball from pitch). For QFN/LGA: per-pad
    rectangular area × n_pads. For SOIC/SOT: leaded gull-wing fillet
    area per lead. Used by build_deck to calibrate per-chip spring
    stiffness."""
    if footprint is None or family is None:
        return 0.5    # generic fallback
    pitch = getattr(footprint, "pitch_mm", None)
    if family in ("bga", "lga", "csp"):
        r = (pitch or 0.5) * 0.3            # ball ≈ 0.6·pitch dia, r = 0.3·pitch
        return math.pi * r * r * max(1, n_pads)
    if family in ("qfn", "son"):
        # Typical QFN pad: pitch × 0.6 × pitch/2 (rough rectangle)
        side = (pitch or 0.5) * 0.5
        return side * side * max(1, n_pads)
    if family in ("soic", "sop"):
        return 0.25 * max(1, n_pads)        # ~0.25 mm² per gull-wing toe
    if family in ("sot",):
        return 0.20 * max(1, n_pads)
    if family == "module":
        return 1.5 * max(1, n_pads)         # large LGA-style module pads
    if family == "copper_pad":
        return 4.0                           # inter-board large copper land
    return 0.3 * max(1, n_pads)
