"""Camera / image-sensor factories.

Where the SamacSys archive doesn't include a KiCad symbol (only a 3D
STEP), pin names are transcribed by hand from the datasheet's pin
table and the geometry comes from the project's own KiCad footprint.
"""

from __future__ import annotations

from smash.state import Chip, Pin, Footprint
from smash.parts._artifacts import (
    pads_from_kicad_mod, outline_polygon, src, datasheet_ref,
)
from smash.parts._slug import canonical_id


# ─────────────────────────────────────────────────────────────────────────
# onsemi AR0234CSSM00SUKA0-CP — 1/2.6" 2.3-MP CMOS image sensor with
# global shutter, 83-ball ODCSP, MIPI CSI-2 + parallel + I²C control.
#
# Pin map transcribed from datasheet `AR0234CSSM00SUKA0-CP.pdf` Table 3
# (PIN DESCRIPTIONS — 83-BALL CSP PACKAGE). The SamacSys archive
# contains ONLY a STEP 3D model — no KiCad symbol — so the pin list
# below is the canonical source.
#
# Footprint is the project-built `ODCSP-83_AR0234CS_10x5_KeyA1.kicad_mod`
# generated by `tools/lib-import/gen_lga_footprint.py` from datasheet
# Case 570CK Issue A.
# ─────────────────────────────────────────────────────────────────────────

# Map of ball coord -> (pin name, pin type, optional voltage_domain note)
# Transcribed verbatim from AR0234CS datasheet Table 3.
_AR0234_PIN_MAP = {
    # MIPI CSI-2 differential outputs
    "C10": ("DATA0_N", "output", None),
    "C9":  ("DATA0_P", "output", None),
    "C11": ("DATA1_N", "output", None),
    "C12": ("DATA1_P", "output", None),
    "E10": ("DATA2_N", "output", None),
    "E9":  ("DATA2_P", "output", None),
    "E12": ("DATA3_N", "output", None),
    "E11": ("DATA3_P", "output", None),
    "D12": ("CLK_N", "clock", None),
    "D11": ("CLK_P", "clock", None),

    # VAA — Analog Power (2.8 V), 4 balls
    "A10": ("VAA", "power", "VAA"),
    "B1":  ("VAA", "power", "VAA"),
    "G2":  ("VAA", "power", "VAA"),
    "G7":  ("VAA", "power", "VAA"),

    # VAA_PHY — Analog PHY (2.8 V)
    "F8":  ("VAA_PHY", "power", "VAA"),

    # Clock / serial-interface power
    "G11": ("EXTCLK", "input", None),
    "C8":  ("VDD_PHY", "power", "VDD"),
    "D10": ("VDDIO_PHY", "power", "VDDIO"),

    # DGND — Digital ground, 13 balls
    **{b: ("DGND", "ground", None) for b in
       ["A2", "A3", "A6", "B2", "C1", "C5", "D8", "D9",
        "E2", "E8", "F2", "F9", "G10"]},

    # GNDIO_PHY — connect to DGND, 2 balls
    "B12": ("GNDIO_PHY", "ground", None),
    "E7":  ("GNDIO_PHY", "ground", None),

    # VDD — Digital Power (1.2 V), 7 balls
    **{b: ("VDD", "power", "VDD") for b in
       ["A4", "A8", "A12", "B10", "D7", "E1", "G8"]},

    # MIPI PHY supply
    "F11": ("VDD_DATA", "power", "VDD"),

    # AGND — Analog ground, 4 balls
    **{b: ("AGND", "ground", None) for b in
       ["A9", "C3", "G3", "G6"]},

    # I²C serial control
    "A5":  ("SADDR", "input", None),
    "F6":  ("SCLK", "io", None),
    "E6":  ("SDATA", "io", None),

    # VAA_PIX — pixel power (2.8 V), 4 balls
    **{b: ("VAA_PIX", "power", "VAA") for b in
       ["B8", "C2", "G1", "G9"]},

    # Frame / line / pixel valid + clock
    "C7":  ("LINE_VALID", "output", None),
    "B7":  ("FRAME_VALID", "output", None),
    "C6":  ("PIXCLK", "clock", None),

    # External shutter / flash strobe
    "F4":  ("SHUTTER", "output", None),
    "E5":  ("FLASH", "output", None),

    # VDD_IO — I/O power (1.8 V or 2.8 V), 8 balls
    **{b: ("VDD_IO", "power", "VDDIO") for b in
       ["A7", "B4", "B5", "B11", "D3", "D6", "F1", "G12"]},

    # Parallel pixel data outputs (DOUT0-9)
    "F3":  ("DOUT0", "output", None),       # LSB
    "G4":  ("DOUT1", "output", None),
    "G5":  ("DOUT2", "output", None),
    "E3":  ("DOUT3", "output", None),
    "D1":  ("DOUT4", "output", None),
    "D2":  ("DOUT5", "output", None),
    "B3":  ("DOUT6", "output", None),
    "E4":  ("DOUT7", "output", None),
    "D4":  ("DOUT8", "output", None),
    "C4":  ("DOUT9", "output", None),       # MSB

    # Test / trigger / output enable
    "F5":  ("TEST", "input", None),         # tie to DGND
    "D5":  ("TRIGGER", "input", None),
    "B6":  ("OE_BAR", "input", None),       # MIPI mode only

    # Reset (active LOW) + reserved + MIPI cap
    "F10": ("RSVD", "input", None),         # 1.5 kΩ to DGND
    "F7":  ("RESET_BAR", "input", None),
    "F12": ("CAP_1UF_PHY", "power", None),

    # Reserved — do not connect, 2 balls
    "A11": ("Reserved", "reserved", None),
    "B9":  ("Reserved", "reserved", None),
}


_AR0234_NOTES_PER_PIN = {
    "F5":  "tie to DGND (manufacturing test enable)",
    "F10": "must connect through 1.5 kΩ to DGND",
    "B6":  "active-low; used for MIPI interface only",
    "F7":  "asynchronous reset, active LOW",
    "F12": "external bypass capacitor for MIPI regulator",
    "A11": "datasheet: 'Reserved (do not connect)'",
    "B9":  "datasheet: 'Reserved (do not connect)'",
    "B12": "datasheet: 'Connect to DGND'",
    "E7":  "datasheet: 'Connect to DGND'",
}


def add_ar0234cssm00suka0_cp(design, ref: str, **overrides) -> Chip:
    """onsemi AR0234CSSM00SUKA0-CP — 1/2.6" 2.3-MP CMOS global-shutter
    image sensor, 83-ball ODCSP (9.995 × 5.595 mm, 0.8 mm pitch, A1
    omitted), MIPI CSI-2 + parallel + I²C control.

    Pin assignments transcribed by hand from datasheet Table 3
    (the SamacSys archive contains only a STEP 3D model, no KiCad
    symbol). Footprint is the project-built `ODCSP-83_AR0234CS`."""
    pn = "AR0234CSSM00SUKA0-CP"
    fp_mod = src(pn, "ODCSP-83_AR0234CS_10x5_KeyA1.kicad_mod")
    pads = pads_from_kicad_mod(fp_mod)

    # Build pins from the hand-typed map. The footprint has all 83 balls.
    pins: list[Pin] = []
    pad_nums = {p.num for p in pads}
    for ball, (name, ptype, vdom) in _AR0234_PIN_MAP.items():
        if ball not in pad_nums:
            # Catches typos in the hand-typed map vs the footprint
            raise ValueError(
                f"{pn}: pin map references ball {ball!r} which is not "
                f"in the footprint pad list")
        pins.append(Pin(
            num=ball, name=name, type=ptype,
            voltage_domain=vdom,
            note=_AR0234_NOTES_PER_PIN.get(ball),
        ))
    # Sanity: every footprint pad has been mapped
    mapped = {p.num for p in pins}
    if mapped != pad_nums:
        missing = pad_nums - mapped
        extra = mapped - pad_nums
        raise ValueError(
            f"{pn}: pin/pad mismatch — missing from map: {missing}, "
            f"extra in map: {extra}")

    fields = dict(
        manf="onsemi", manf_pn=pn, canonical_id=canonical_id(pn), name=pn, value=pn,
        description=(
            "CMOS image sensor, 1/2.6\" 2.3 MP (1920×1200), global "
            "shutter, MIPI CSI-2 (1/2/4-lane) + parallel + 2-wire "
            "control, 83-ball ODCSP (9.995×5.595 mm)"
        ),
        datasheet=datasheet_ref(pn, f"{pn}.pdf"),
        package="ODCSP-83 (9.995 × 5.595 mm)",
        size_mm=(9.995, 5.595),
        temp_range_c=(-40, 85),
        # ── thermal (onsemi AR0234CS DS rev 0 Mar 2020 §Specs p1) ────
        # DS headline quotes "<420 mW" total operational power. From
        # the per-rail currents in Tab 14 (MIPI, 120 fps full res):
        #   IDD (1.2V) 155 mA typ → 186 mW
        #   IAA (2.8V)  55 mA typ → 154 mW
        #   IAA_PIX, IDD_IO_PHY etc → ~30 mW
        # = ~370 mW typical, peaks toward 0.6 W at max current.
        # No ΘJC quoted in DS (CSP package, no thermal pad).
        p_active_w=0.37,                    # MIPI 120 fps full res typical (DS Tab 14 p17)
        p_max_w=0.42,                       # DS-quoted "<420 mW" operational cap (DS p1)
        rth_jc_cw=10.0,                     # *estimate (NOT DS) — ODCSP-83
                                            # sensor package-class typical;
                                            # the DS gives no thermal table
        tj_max_c=105.0,                     # max junction op, DS Specs table p1
        standards=["RoHS"],
        pins=pins,
        footprint=Footprint(
            name="ODCSP-83_AR0234CS_10x5_KeyA1",
            package_class="ODCSP-83 BGA",
            pads=pads,
            body_outline=outline_polygon(fp_mod, "F.Fab"),
            courtyard=outline_polygon(fp_mod, "F.CrtYd"),
            pitch_mm=0.8,
            size_mm=(9.995, 5.595),
            model_3d_path=datasheet_ref(pn, f"{pn}.stp"),
            source="project (gen_lga_footprint.py from datasheet "
                   "Case 570CK Issue A)",
            note=(
                "ODCSP-83: 7-row × 12-col ball grid with A1 omitted "
                "(orientation key). 0.4 mm circle pads, 0.8 mm pitch. "
                "Footprint generated by tools/lib-import/gen_lga_footprint.py."
            ),
        ),
        note=(
            "AR0234CS = 1/2.6\" 2.3 Mp CMOS global-shutter image sensor. "
            "Pin map below transcribed verbatim from datasheet Table 3 "
            "(83-ball CSP). MIPI CSI-2 supports 1, 2, or 4 lanes "
            "(DATA0..DATA3 differential pairs + CLK pair). Parallel "
            "interface exposes DOUT0 (LSB) through DOUT9 (MSB).\n\n"
            "Power rails (4 distinct domains):\n"
            "  VAA      : 2.8 V analog power (4 balls: A10, B1, G2, G7)\n"
            "  VAA_PIX  : 2.8 V pixel power (4 balls)\n"
            "  VAA_PHY  : 2.8 V analog PHY power (F8)\n"
            "  VDD      : 1.2 V digital (7 balls)\n"
            "  VDD_PHY  : 1.2 V MIPI PHY (C8)\n"
            "  VDD_DATA : 1.2 V MIPI PHY power (F11)\n"
            "  VDDIO_PHY: 1.8 V I/O (D10)\n"
            "  VDD_IO   : 1.8 V or 2.8 V I/O (8 balls)\n\n"
            "Per datasheet recommendation: tie VDD_PHY+VDD_DATA to "
            "VDD (1.2 V); tie VAA_PHY to 2.8 V (=VAA); VDDIO_PHY=1.8 V.\n\n"
            "Default I²C slave address 0x20/0x21; alternate 0x30/0x31 "
            "via SADDR strap."
        ),
    )
    fields.update(overrides)
    return design.add_chip(ref=ref, **fields)
