"""Project-built custom footprint factories — mechanical, connector, and
flex-antenna parts whose `.kicad_mod` lives in `library_kicad/footprints.pretty/`
(originally generated by `tools/lib-import/gen_lga_footprint.py` or
`gen_nfc_antenna.py`, then hand-tuned).

These are all `Chip` records with a Footprint but minimal datasheet
data — they describe physical interfaces on the Smash board, not real
silicon parts.
"""

from __future__ import annotations

import functools
import math

from smash.state import Chip, Pin, Footprint
from smash.parts._artifacts import (
    pads_from_kicad_mod, outline_polygon, src, datasheet_ref,
)


def _project_footprint(part_dir: str, fp_name: str, *,
                       package_class: str, height_mm: float | None = None,
                       size_mm: tuple | None = None,
                       pitch_mm: float | None = None,
                       note: str = "") -> Footprint:
    """Common builder for project-built footprints. Pads + outline +
    courtyard parsed directly from the `.kicad_mod`.

    `.kicad_mod` F.CrtYd polygons sometimes hug the pads (or are absent),
    so the courtyard is normalised to clear the lands by >= the standard
    ring — the packer abuts courtyards, and a tight one shorts a dense
    field (e.g. the 45-up pogo bench)."""
    fp_mod = src(part_dir, f"{fp_name}.kicad_mod")
    return Footprint(
        name=fp_name,
        package_class=package_class,
        pads=pads_from_kicad_mod(fp_mod),
        body_outline=outline_polygon(fp_mod, "F.Fab"),
        courtyard=outline_polygon(fp_mod, "F.CrtYd"),
        pitch_mm=pitch_mm,
        size_mm=size_mm,
        height_mm=height_mm,
        model_3d_path=None,
        source="project (library_kicad/footprints.pretty/)",
        note=note,
    ).ensure_courtyard_clearance()


def _pins_from_pads(footprint: Footprint, name_map: dict | None = None) -> list:
    """Default Pin list: one Pin per UNIQUE pad num. A KiCad footprint
    can have multiple Pad entries sharing the same num (e.g. a stitched
    thermal pad, or a multi-via net jumper) — those collapse to a
    single Pin in the design's electrical model.

    If `name_map` is given, it overrides the pin name per pad-num;
    otherwise pin name == pad num.
    """
    name_map = name_map or {}
    seen: set = set()
    pins = []
    for pad in footprint.pads:
        if pad.num in seen:
            continue
        seen.add(pad.num)
        pins.append(Pin(
            num=pad.num,
            name=name_map.get(pad.num, pad.num),
        ))
    return pins


# ═════════════════════════════════════════════════════════════════════════
# CellAttach_3x2_TLM1520 — solder-tab pad cluster for the 3× TLM-1520HPM/S
# primary-cell pack
# ═════════════════════════════════════════════════════════════════════════

def add_cellattach_3x2_tlm1520(design, ref: str = "P_CELLS",
                               **overrides) -> Chip:
    """3×2 solder-tab pad cluster for the TLM-1520HPM/S battery pack
    on `power_board`'s bottom face. Six 3.0 × 2.0 mm SMD pads at the
    cell tab positions (±6 mm X, ±4 mm Y).

    Default ref `P_CELLS` follows the project convention: refs starting
    with `P_` are bottom-face mating-pad clusters (auto-routed by the
    placer to the back of the board).

    Pad role mapping (per `add_battery_cells()` in system.py):
      Cell 1: pad 1 = +, pad 2 = -
      Cell 2: pad 3 = +, pad 4 = -
      Cell 3: pad 5 = +, pad 6 = -
    Each '+' tab feeds a 200 mΩ isolation resistor that combines to
    BAT_RAW; each '-' ties to GND.
    """
    part = "CellAttach_3x2_TLM1520"
    fp = _project_footprint(
        part, "CellAttach_3x2_TLM1520",
        package_class="Cell-attach pad cluster (6× 3.0×2.0 mm)",
        size_mm=(12.0, 7.0),
        note="3 columns × 2 rows of solder-tab pads. Columns ±4.5 X "
             "(1.5 mm gap between cells); rows ±2.5 Y (3 mm gap between "
             "+ and − tabs).",
    )
    pins = _pins_from_pads(fp, name_map={
        "1": "CELL1+", "2": "CELL1-",
        "3": "CELL2+", "4": "CELL2-",
        "5": "CELL3+", "6": "CELL3-",
    })
    fields = dict(
        manf="project", manf_pn=part,
        name="CellAttach_3x2_TLM1520",
        description=(
            "Solder-tab pad cluster for 3× TLM-1520HPM/S battery pack — "
            "bottom face of power_board. 3.0×2.0 mm pads, 12.0 mm X-pitch "
            "and 8.0 mm Y-spacing between cell + and − tabs."
        ),
        datasheet=None,
        package="Custom 3×2 solder-tab cluster",
        pins=pins,
        footprint=fp,
        note=(
            "Used by `power_board.add_battery_cells()`. Each cell's "
            "+ terminal ties through a 200 mΩ isolation resistor (also "
            "on power_board) so a single tab failure can't short the "
            "pack. − terminals tie directly to GND."
        ),
    )
    fields.update(overrides)
    return design.add_chip(ref=ref, **fields)


# ═════════════════════════════════════════════════════════════════════════
# BatteryContacts_3 — three + contact pads at the cell-centre triangle
# ═════════════════════════════════════════════════════════════════════════

def add_cell_contacts_3(design, ref: str = "P_CELL_CONTACTS",
                        **overrides) -> Chip:
    """Three round battery + contact pads, one at each Ø14.8 cell's centre
    (the 3 cells sit in a triangle around the spin axis), on the
    battery-connector tile (activation_interface). Each cell's + side solder
    tab (factory-welded to the top button) reflows onto its pad; the cell −
    side tabs land on the three P_CELL_TAB_NEG* solder-tab pads on the thin
    cell_floor_board the cells stand on, so there are NO ground pads here.
    Replaces the old P_CELLS solder-tab cluster.

    Pad k = CELLk+ → BAT_CELLk_POS (→ 200 mΩ iso R → BAT_RAW). The contact
    triangle (CLUSTER_R) must match `_mark_battery_pockets`' cell-bore centres
    so each pad seats on the cell below it."""
    from smash.state.pad import Pad
    CLUSTER_R = 8.6      # mm — cell-centre radius (matches the bore centres)
    PAD_DIA = 6.0        # mm — contact onto the cell's top terminal
    centres = [(CLUSTER_R * math.cos(math.pi / 2 + 2 * math.pi * k / 3),
                CLUSTER_R * math.sin(math.pi / 2 + 2 * math.pi * k / 3))
               for k in range(3)]
    pads = [Pad(num=str(k + 1), position_mm=centres[k],
                size_mm=(PAD_DIA, PAD_DIA), shape="circle", layer="F.Cu")
            for k in range(3)]
    fp = Footprint(
        name="BatteryContacts_3", pads=pads,
        package_class="Battery + contacts (3× Ø6)",
        source="project (battery connector)",
        note="3 round + contacts at the cell-centre triangle (CLUSTER_R=8.6 mm); "
             "cell − returns on the backbone GND LGA land.")
    fp.ensure_courtyard_clearance()       # no F.CrtYd authored — ring the pads
    fields = dict(
        manf="project", manf_pn="BatteryContacts_3", name="BatteryContacts_3",
        description=("3 round battery + contact pads at the cell-centre "
                     "triangle — battery-connector tile (activation_interface)"),
        datasheet=None, package="Custom 3-contact cluster",
        pins=[Pin(num=str(k + 1), name=f"CELL{k + 1}+") for k in range(3)],
        footprint=fp,
        note=("Battery-connector + contacts (replaces P_CELLS). Each pad → "
              "BAT_CELLk_POS → 200 mΩ iso R → BAT_RAW; cell − returns via the "
              "P_CELL_TAB_NEG* side solder-tab lands on aft_end_board."))
    fields.update(overrides)
    return design.add_chip(ref=ref, **fields)


# ═════════════════════════════════════════════════════════════════════════
# CellSolderTab — one side solder-tab landing pad per cell terminal
# ═════════════════════════════════════════════════════════════════════════
# (add_cell_contacts_1h — the legacy 27 mm 2-pad horizontal-cell cluster on the
# deleted cell_floor_board — is GONE; the discrete tab pads below replaced it.)

def add_cell_solder_tab(design, ref: str = "P_CELL_TAB", **overrides) -> Chip:
    """ONE cell SIDE SOLDER-TAB landing pad on the battery-floor tile's top
    face (placeholder Ø3 — the real tab-land footprint is TBD). The cells
    are ordered with factory-welded side tabs instead of end pins
    (2026-07-30): the tab exits the can side, bends down to the floor, and
    reflows onto this pad — nothing protrudes from the cell bottom, so the
    cell base rests flat on the floor tile. As DISCRETE chips each tab
    claims only its own ~Ø3 footprint (no wide multi-pad span reserving the
    board centre). Positioned via locked_placements: single mode = the two
    cell ends on the N–S axis (floor = aft_end_board); triple mode = the
    trefoil valleys (floor = the thin cell_floor_board). `height_mm` models
    the formed tab loop above the pad so the battery spacers get a
    clearance chimney over it (_mark_battery_chip_clearance)."""
    from smash.state.pad import Pad
    pad = Pad(num="1", position_mm=(0.0, 0.0), size_mm=(3.0, 3.0),
              shape="circle", layer="F.Cu")
    fp = Footprint(
        name="CellSolderTab_placeholder", pads=[pad],
        package_class="Cell side solder-tab land (placeholder Ø3)",
        source="project (battery solder tab, footprint TBD)",
        note="Placeholder Ø3 — the cell's side solder tab reflows here; "
             "swap for the real tab-land footprint when available.")
    fp.ensure_courtyard_clearance()
    fields = dict(
        manf="project", manf_pn="CellSolderTab", name="CellSolderTab",
        description="Battery cell side solder-tab land (placeholder) — battery-floor tile",
        datasheet=None, package="Custom cell solder-tab land (placeholder)",
        pins=[Pin(num="1", name="TAB")],
        footprint=fp,
        height_mm=1.5,      # formed tab loop above the pad → spacer chimney
        note="One cell side solder-tab → land on the battery-floor tile. Real footprint TBD.")
    fields.update(overrides)
    return design.add_chip(ref=ref, **fields)


# ═════════════════════════════════════════════════════════════════════════
# SMD10T04R111 — Steminc Ø10×0.4 PZT disc, the aft piezo shock/launch sensor
# ═════════════════════════════════════════════════════════════════════════

def add_piezo_disc_smd10t04r111(design, ref: str = "P_PIEZO",
                                **overrides) -> Chip:
    """Steminc SMD10T04R111 — Ø10 × 0.4 mm bare PZT disc (SM111, Navy
    Type I hard PZT, Curie ~320 °C) with WRAP-AROUND electrode ("R"
    config): both terminals on one face, so the disc reflows onto two
    SMD pads like any chip — no leads, no glue, no milled pocket (the
    pocket existed to recess the old CEB-21018 brass diaphragm and give
    it flex room; a rigid bonded disc needs neither).

    Sits on `aft_end_board`'s TOP face on the spin
    axis = the battery-compartment floor in single-cell mode, so it
    joins the cells' In52/Sn48 118 °C step (PZT must never see a SAC
    reflow — depoling risk above ~Curie/2) and is potted with them.

    Sensing: bonded-compression mode. V ≈ d33·ρ·a·t²/ε — thickness²,
    diameter-independent: ~5–7 V at 20 kG vs the 0.30 V comparator
    threshold. Static capacitance 2100 pF ±15 % → 1 MΩ bleed gives a
    ~75 Hz high-pass corner (launch edge passes clean).

    Pad map:
      pad 1 = MAIN (bottom electrode)          → `PIEZO_P`
      pad 2 = WRAP (top electrode, wrapped)    → GND

    ⚠ The wrap-electrode strip geometry below is a conservative
    placeholder — confirm against the Steminc spec sheet before fab
    (Research/ PDF TODO; their per-model drawings are on request)."""
    part = "SMD10T04R111"
    fp = _project_footprint(
        part, "PiezoDisc_SMD10T04R111",
        package_class="Piezo disc Ø10×0.4 mm, wrap-around electrode (SMD)",
        size_mm=(10.0, 10.0),
        height_mm=0.4,
        note="2 SMD pads under the Ø10 disc: main electrode (centre-offset "
             "Ø5 round) + wrap strip (2.5×1.6 at the east rim). Electrode "
             "split per Steminc R config — verify strip position against "
             "the factory drawing before fab.",
    )
    # The .kicad_mod draws the body/courtyard as fp_circle, which
    # outline_polygon doesn't parse — set the round outlines here (same
    # pattern as the NFC coil factory) so footprint_bbox_mm sees the FULL
    # Ø10 disc, not just the pad cluster: the spacer chip-clearance cut and
    # the LGA land packing both key on that bbox (the rigid disc must not
    # be pressed by the spacer ring).
    _Rb, _Rc = 5.0, 5.25
    fp.body_outline = [(_Rb * math.cos(math.radians(a)),
                        _Rb * math.sin(math.radians(a)))
                       for a in range(0, 360, 10)]
    fp.courtyard = [(_Rc * math.cos(math.radians(a)),
                     _Rc * math.sin(math.radians(a)))
                    for a in range(0, 360, 10)]
    pins = _pins_from_pads(fp, name_map={"1": "MAIN", "2": "WRAP"})
    fields = dict(
        manf="Steminc", manf_pn="SMD10T04R111",
        name="SMD10T04R111",
        description=(
            "Steminc piezo ceramic disc Ø10 × 0.4 mm, SM111 (Navy I hard "
            "PZT), wrap-around electrode — SMD-mount launch/impact shock "
            "sensor, 2100 pF, 5 MHz thickness resonance"
        ),
        datasheet="Research/SMD10T04R111.pdf",   # TODO: request from Steminc
        package="Bare PZT disc Ø10×0.4, both electrodes one face",
        size_mm=(10.0, 10.0), height_mm=0.4,
        pins=pins,
        footprint=fp,
        note=(
            "MAIN electrode feeds the sense node (R_COMP_SER → TLV3691 "
            "launch-detect comparator, same tile); WRAP (top electrode, "
            "brought around) ties to GND. A piezoelectric accelerometer — "
            "reads launch setback (+g) and impact (−g); complements the "
            "H3LIS331 high-G accel (quantitative but I²C — no µs-class "
            "hardware edge). In-Sn solder only: SAC reflow risks depoling "
            "the PZT and exceeds nothing else but joins the battery-close "
            "step. Listed 2 pc/set at Steminc; Ø5 SMD05T04R411 is the "
            "drop-in fallback if unavailable."
        ),
    )
    fields.update(overrides)
    return design.add_chip(ref=ref, **fields)


# ═════════════════════════════════════════════════════════════════════════
# Pogo_Pad_D2.0mm — 2 mm round pogo TestPoint (22× on activation_interface)
# ═════════════════════════════════════════════════════════════════════════

def add_pogo_pad(design, ref: str, square: bool = False, **overrides) -> Chip:
    """2 mm pogo TestPoint. Used on the aft bench array and on
    `activation_interface` as a dev-fixture pogo landing pad
    (silkscreen-grouped by purpose).

    Caller picks the `ref` (e.g. TP_BAT, TP_3V3, TP_SWDIO) and wires
    pin 1 to whatever signal is being exposed.

    `square=True` selects the SQUARE silhouette, which marks the FIRST
    pad of a silkscreen group — the pin-1 convention every bench user
    already reads without a legend. Both variants are 2.0 mm across and
    sit on the same pitch, so the pad field stays uniform and a pogo
    fixture is unaffected: only the silhouette differs.
    """
    part = "Pogo_Pad_S2.0mm" if square else "Pogo_Pad_D2.0mm"
    fp = _project_footprint(
        part, part,
        package_class=("Pogo TestPoint (2 mm square, group start)"
                       if square else "Pogo TestPoint (2 mm Ø)"),
        size_mm=(2.0, 2.0),
        note=("Single SMD square pad, 2.0 mm — group-start marker."
              if square else "Single SMD circle pad, 2.0 mm Ø."),
    )
    fields = dict(
        manf="project", manf_pn=part, name=part,
        description=("2 mm square pogo-pad TestPoint (group start)"
                     if square else "2 mm Ø round pogo-pad TestPoint"),
        datasheet=None,
        package="Custom square pad" if square else "Custom round pad",
        pins=_pins_from_pads(fp, name_map={"1": "TP"}),
        footprint=fp,
        note=(
            "Used by `add_activation_interface_board()` for the 22-pad "
            "bench-fixture pogo landing cluster. Each pogo pad gets its "
            "own ref (TP_BAT, TP_3V3, TP_SWDIO, TP_CAN_P, etc.). The "
            "grouping (CRITICAL / SWD / CAN / ext I²C+GPIO / power "
            "passthrough) is silkscreen-boxed on the activation tile, "
            "not in the chip-level model — handled by the placer."
        ),
    )
    fields.update(overrides)
    return design.add_chip(ref=ref, **fields)


# NOTE: the 24-pad LGA-24 inter-board connectors (`P_AFT_LGA`,
# `J_AFT_LGA`, `J_NOSE_LGA`) have been retired from the design.
# `P_AFT_LGA` / `J_AFT_LGA` went away when the activation_interface
# became flex-connected to power_board. `J_NOSE_LGA` was first broken
# out into 11 `add_pogo_pad()` calls on the nose tile, then those too
# were retired — the `nose_cap` is now a UJ20 USB-C receptacle
# (`J_USB_C`, depot service port). `add_pogo_pad` survives for the aft
# TestPoint bench array on activation_interface. The LGA factory
# functions are deleted; the corresponding footprint sources under
# `parts/sources/LGA-24_*Payload_*/` were removed.


# ═════════════════════════════════════════════════════════════════════════
# Spacer_Mechanical_34mm — 6× per build, structural rigid disc
# ═════════════════════════════════════════════════════════════════════════

def add_mechanical_spacer_34mm(design, ref: str, **overrides) -> Chip:
    """Ø34 mm rigid disc with chip-clearance cavities milled on both
    faces. Bridges one snake-fold gap so launch-G axial loads don't
    crush stacked chips into each other.

    Six instances per Smash build (one per inter-tile fold). The
    footprint carries a single GND-tied SMD pad as a SKiDL placeholder
    — purely so the netlist accounts for the part. No real electrical
    function.
    """
    part = "Spacer_Mechanical_34mm"
    fp = _project_footprint(
        part, "Spacer_Mechanical_34mm",
        package_class="Mechanical spacer (Ø34 mm rigid disc)",
        size_mm=(34.0, 34.0),
        height_mm=None,
        note=(
            "Ø34 mm rigid disc with chip-clearance cavities milled on "
            "both faces. Single 0.8 mm Ø GND pad for netlist completeness."
        ),
    )
    fields = dict(
        manf="project", manf_pn=part, name=part,
        description=(
            "Mechanical spacer disc (Ø34 mm rigid PCB substrate, "
            "chip-clearance cavities both faces). 6× per Smash build."
        ),
        datasheet=None,
        package="Custom Ø34 mm rigid disc",
        pins=_pins_from_pads(fp, name_map={"1": "GND_TIE"}),
        footprint=fp,
        note=(
            "Purely mechanical part. Six instances per build, one per "
            "accordion-fold pair on the snake-folded rigid-flex assembly. "
            "Single GND-tied pad is a netlist placeholder — the spacer "
            "carries no live signal."
        ),
    )
    fields.update(overrides)
    return design.add_chip(ref=ref, **fields)


# ═════════════════════════════════════════════════════════════════════════
# NFC_Antenna_Flex_27x50 — flex-only 4-turn etched spiral antenna
# ═════════════════════════════════════════════════════════════════════════

def _nfc_spiral_points(
    width_mm: float, length_mm: float, turns: int,
    trace_mm: float, gap_mm: float,
    edge_clearance_mm: float = 0.5,
    start_xy: tuple | None = None,
    terminate_y: float | None = None,
) -> tuple:
    """Generate the rectangular-spiral polyline plus inner-end position.

    Returns `(points, inner_end_xy)`. The spiral winds CW from the
    outer top-left corner. `inner_end_xy` is the innermost terminus
    where the AC1 bridge picks up (a via to B.Cu).

    If `start_xy` is supplied, the polyline is prefixed with a two-
    segment lead-in (east to the spiral's outer west edge, then north
    to the top-left corner) so the trace visibly originates at the
    AC0 feed pad.

    If `terminate_y` is supplied (typically the y-coord of the AC1
    pad), the final turn keeps descending the inner west edge to that
    y so the B.Cu bridge from AC1 lands a short horizontal stub away
    from the inner spiral. Without it, the final segment stops half
    a pitch below the inner top corner.

    Nesting is done by climbing the west edge stopping `pitch` short
    of the top, then stepping right by `pitch` into the next inner
    top-left corner. Skipping that climb (jumping diagonally between
    turns) produces a visible "shortcut" in the corner — see
    https://github.com/.../issue if it reappears.
    """
    pitch = trace_mm + gap_mm
    inset = edge_clearance_mm + trace_mm / 2
    x_max = width_mm / 2 - inset
    y_max = length_mm / 2 - inset
    x_min, y_min = -x_max, -y_max

    pts: list[tuple] = []
    if start_xy is not None:
        sx, sy = start_xy
        pts.append(start_xy)
        # Lead-in stays OUTSIDE the spiral's outer west edge: go
        # straight up the pad's own column to the spiral's top y, then
        # a short east stub joins the outer top-left corner. Routing
        # via (x_min, sy) instead would lay the lead-in on top of the
        # spiral's first-turn west edge — a visible overlap from
        # y=sy up to (y_max - pitch).
        pts.append((sx, y_max))

    pts.append((x_min, y_max))   # outer top-left corner
    for turn in range(turns):
        pts.append((x_max, y_max))    # top edge, west → east
        pts.append((x_max, y_min))    # east edge, north → south
        pts.append((x_min, y_min))    # bottom edge, east → west
        if turn < turns - 1:
            # West edge, climbing back up but stopping pitch short of
            # the start so the next turn can nest cleanly inside.
            pts.append((x_min, y_max - pitch))
            # Step right by pitch — this lands exactly at the next
            # turn's top-left corner.
            x_max -= pitch; y_max -= pitch
            x_min += pitch; y_min += pitch
            pts.append((x_min, y_max))
        else:
            # Innermost turn. Either descend to the user-specified
            # terminate_y (aligns with the AC1 pad) or fall back to a
            # short half-pitch stub.
            if terminate_y is not None:
                pts.append((x_min, terminate_y))
            else:
                pts.append((x_min, y_max - pitch / 2))

    inner_end = pts[-1]
    return pts, inner_end


_NFC_W, _NFC_H = 20.0, 35.0
_NFC_TURNS, _NFC_TRACE, _NFC_GAP = 8, 0.3, 0.3

# Round coil (operates like the camera tile so it S-folds): Ø22 disc,
# 0.2/0.2 mm trace/gap, 17 turns → L ≈ 4.82 µH, which resonates at
# 13.56 MHz against the ST25DV16KC's fixed internal Ctun = 28.5 pF (no
# external trim cap). Solved with the Mohan current-sheet model; see
# memory ref_st25dv_antenna_L.
_NFC_DIA = 22.0
_NFC_TURNS_R, _NFC_TRACE_R, _NFC_GAP_R = 17, 0.2, 0.2
_NFC_EDGE_CLEAR_R = 0.5


def _nfc_round_spiral_points(diameter_mm: float, turns: int,
                             trace_mm: float, gap_mm: float,
                             edge_clearance_mm: float = 0.5,
                             start_angle_deg: float = 90.0,
                             seg_per_turn: int = 48,
                             start_xy: tuple | None = None) -> tuple:
    """Archimedean circular spiral `r(θ) = r_out − (pitch/2π)·θ` as a
    segmented polyline winding inward from the outer edge. Returns
    `(points, inner_end_xy)`. `start_angle_deg` sets the outer terminus
    (90° = North) so the feed pads sit just outboard of it; `start_xy`
    prepends a short radial lead-in from the AC0 pad."""
    pitch = trace_mm + gap_mm
    r_out = diameter_mm / 2.0 - edge_clearance_mm - trace_mm / 2.0
    a0 = math.radians(start_angle_deg)
    pts: list[tuple] = []
    if start_xy is not None:
        pts.append(start_xy)
    steps = max(1, int(seg_per_turn * turns))
    for i in range(steps + 1):
        frac = i / steps
        theta = a0 + 2.0 * math.pi * turns * frac     # wind inward (CCW)
        r = r_out - pitch * turns * frac
        pts.append((r * math.cos(theta), r * math.sin(theta)))
    return pts, pts[-1]


def _reflect(geom, *, fx=1.0, fy=1.0):
    p1, p2, spiral, inner = geom
    f = lambda xy: (fx * xy[0], fy * xy[1])
    return f(p1), f(p2), tuple(f(p) for p in spiral), f(inner)


@functools.lru_cache(maxsize=None)
def _nfc_geometry(feed_edge: str):
    """Pad + spiral geometry for the antenna whose feed sits on
    `feed_edge` (the flex-entry side). Cached — the coil is deterministic
    per edge, so the generated "NFC tag" for each orientation is computed
    once and reused.

    Round Ø22 coil (see `_nfc_round_spiral_points`). `north` is canonical
    — the two feed pads sit just outboard of the spiral's North outer
    terminus; AC0 feeds the outer end, AC1 bridges to the inner terminus
    on B.Cu. Other edges rotate the start angle. Returns
    `(pad1_xy, pad2_xy, spiral_pts, spiral_inner_xy)`."""
    r_out = _NFC_DIA / 2.0 - _NFC_EDGE_CLEAR_R - _NFC_TRACE_R / 2.0
    start_angle = {"north": 90.0, "south": -90.0,
                   "east": 0.0, "west": 180.0}.get(feed_edge)
    if start_angle is None:
        raise ValueError(f"unknown NFC feed_edge {feed_edge!r} "
                         "(expected north/south/east/west)")
    # Outer terminus + the two feed pads just outboard of it, offset
    # tangentially so AC0/AC1 sit side by side off the disc edge.
    a = math.radians(start_angle)
    ux, uy = math.cos(a), math.sin(a)          # radial (outward)
    tx, ty = -uy, ux                           # tangential
    # Pads sit in the gap between the outer turn (r_out) and the disc rim,
    # so they stay on-board and clear of the inner turns.
    r_pad = (r_out + _NFC_DIA / 2.0) / 2.0
    p1 = (r_pad * ux - 0.5 * tx, r_pad * uy - 0.5 * ty)   # AC0 feed
    p2 = (r_pad * ux + 0.5 * tx, r_pad * uy + 0.5 * ty)   # AC1 bridge
    spiral, inner = _nfc_round_spiral_points(
        _NFC_DIA, _NFC_TURNS_R, _NFC_TRACE_R, _NFC_GAP_R,
        edge_clearance_mm=_NFC_EDGE_CLEAR_R,
        start_angle_deg=start_angle, start_xy=p1)
    return p1, p2, tuple(spiral), inner


def add_nfc_antenna_flex_27x50(design, ref: str = "L_NFC_ANT",
                               feed_edge: str = "north",
                               **overrides) -> Chip:
    """Flex-only 17-turn ROUND spiral antenna for NFC, Ø22 mm.

    `feed_edge` selects which disc edge the two AC0/AC1 feed pads sit on
    — the edge the rigid-flex strip launches from. The per-edge geometry
    is cached (`_nfc_geometry`).

    Sized to L ≈ 4.82 µH (Mohan current-sheet, Ø22 / 0.2 mm trace / 0.2 mm
    gap / 17 turns), which resonates at 13.56 MHz against the ST25DV16KC's
    FIXED internal Ctun = 28.5 pF — no external trim cap (the chip has no
    trim pin). Memory ref_st25dv_antenna_L.

    The round form (vs the old 20×35 rect) lets the NFC tile behave like
    the camera/qpd tiles — a small Ø22 disc that S-folds off the snake
    flex instead of claiming a full grid cell.

    Two electrical pins (AC0/AC1). The .kicad_mod from gen_nfc_antenna.py
    was generated for the old 27×50 rect footprint — body_outline,
    courtyard and copper are overridden here to the round coil.
    """
    part = "NFC_Antenna_Flex_27x50"   # KiCad lib id kept for net-list compat
    fp = _project_footprint(
        part, "NFC_Antenna_Flex_27x50",
        package_class="NFC spiral antenna (flex copper)",
        size_mm=(_NFC_DIA, _NFC_DIA),
        note=(
            "17-turn round spiral, Ø22 mm, 0.2 mm trace + 0.2 mm gap. "
            "Two SMD feed pads just outboard of the coil (flex-entry "
            "side). L ≈ 4.82 µH, resonates at 13.56 MHz against the "
            "ST25DV16KC's fixed 28.5 pF internal Ctun (no trim cap)."
        ),
    )
    # The .kicad_mod's body_outline + courtyard target the old 27×50
    # rect; override with the round Ø22 disc.
    R = _NFC_DIA / 2.0
    crt = 0.25       # IPC-7351 standard courtyard clearance
    circ = [(R * math.cos(t), R * math.sin(t))
            for t in (math.radians(d) for d in range(0, 360, 10))]
    fp.body_outline = circ
    fp.courtyard = [((R + crt) * math.cos(t), (R + crt) * math.sin(t))
                    for t in (math.radians(d) for d in range(0, 360, 10))]
    # Feed pads + spiral for the requested flex-entry edge (cached).
    pad1_pos, pad2_pos, spiral_pts, spiral_inner = _nfc_geometry(feed_edge)
    spiral_pts = list(spiral_pts)          # detach from the cached tuple
    fp.copper_lines.append({
        "layer":    "F.Cu",
        "width_mm": _NFC_TRACE_R,
        "points":   spiral_pts,
    })

    for p in fp.pads:
        # SMD feed pads move to the north edge (flex-launch side).
        if p.num == "1" and p.shape == "rect":
            p.position_mm = pad1_pos
        elif p.num == "2" and p.shape == "rect":
            p.position_mm = pad2_pos
        # Two PTH bridge vias come from the .kicad_mod's old 27×50
        # geometry. Re-target them: one moves to the AC1 SMD pad (so
        # the F.Cu pad → B.Cu via is colocated); the other follows the
        # spiral to its new inner-end location.
        elif p.num == "2" and p.shape == "circle":
            old_x = p.position_mm[0]
            # In the source mod, the SMD-colocated via is at x=12.25
            # and the inner-end via is at x=11.05. Use position to
            # tell them apart.
            if abs(old_x - 12.25) < 0.5:
                p.position_mm = pad2_pos
            else:
                p.position_mm = spiral_inner

    # B.Cu bridge: AC1 pad's via → spiral inner-end via. The via at
    # `spiral_inner` brings the signal back up to F.Cu where the
    # spiral terminates internally.
    fp.copper_lines.append({
        "layer":    "B.Cu",
        "width_mm": _NFC_TRACE_R,
        "points":   [pad2_pos, spiral_inner],
    })
    fields = dict(
        manf="project", manf_pn=part, name=part,
        description=(
            "Flex spiral antenna for NFC (13.56 MHz), Ø22 mm, "
            "17-turn round, ~4.82 µH typical inductance"
        ),
        datasheet=None,
        package="Custom flex spiral",
        # Inductance drives ST25DV16KC resonance (fixed 28.5 pF Ctun).
        inductance_h=4.82e-6,
        pins=_pins_from_pads(fp, name_map={"1": "AC0", "2": "AC1"}),
        footprint=fp,
        note=(
            "Generated by `tools/lib-import/gen_nfc_antenna.py`, reshaped "
            "to a round Ø22 coil. Resonates at 13.56 MHz against "
            "ST25DV16KC's AC0/AC1 with its FIXED internal 28.5 pF Ctun — "
            "no external trim cap. Sits on the cylinder wall behind a "
            "housing window at the NFC location (no Al eddy currents)."
        ),
    )
    fields.update(overrides)
    return design.add_chip(ref=ref, **fields)


# ═════════════════════════════════════════════════════════════════════════
# Marktech MT03-092 — Si quadrant photodiode, TO-8 6-lead
# (Custom-built TO-8 footprint, not a SamacSys part)
# ═════════════════════════════════════════════════════════════════════════

def add_mt03_092_qpd(design, ref: str = "U_QPD", **overrides) -> Chip:
    """Marktech MT03-092 — silicon quadrant photodiode in TO-8 6-lead
    package. 4 quadrant anodes + 1 common cathode + 1 NC. 

    Photovoltaic mode: common cathode → QPD_VREF (the same mid-rail the
    TIAs servo the anodes to — true zero bias; cathode-to-GND would
    forward-bias every quadrant), each anode → TIA input (4× AD8603
    op-amps wired as transimpedance amplifiers on the same flex tile).

    Pin map per the datasheet schematic (DS p2, NOT sequential): pin 2 is
    the common cathode (backside butt weld), pin 5 is NC; the quadrant
    anodes are Q1→4, Q2→6, Q3→3, Q4→1.
    """
    part = "MT03_092_QPD_TO8"
    fp = _project_footprint(
        part, "MT03_092_QPD_TO8",
        package_class="TO-8 6-lead (through-hole)",
        size_mm=(15.4, 15.4),
        height_mm=None,
        note=(
            "6 through-hole pads in TO-8 outline (Ø15.4 mm), two rows "
            "of 3 at 2.54 mm pitch, rows 10.16 mm apart (DS p2). "
            "Pads 4/6/3/1 = quadrant anodes Q1/Q2/Q3/Q4, pad 2 = "
            "common cathode (backside butt weld), pad 5 = NC. Pin "
            "numbering follows datasheet."
        ),
    )
    fields = dict(
        manf="Marktech", manf_pn="MT03-092", name="MT03-092",
        description=(
            "Silicon quadrant photodiode, 8 mm active area (4× 4 mm² "
            "quadrants, 200 µm gaps), 1064 nm peak sensitivity, TO-8 "
            "6-lead through-hole"
        ),
        datasheet="Research/MT03-092.pdf",
        package="TO-8 6-lead",
        pins=_pins_from_pads(fp, name_map={
            "1": "ANODE_Q4", "2": "CATHODE_COM",
            "3": "ANODE_Q3", "4": "ANODE_Q1",
            "5": "NC", "6": "ANODE_Q2",
        }),
        footprint=fp,
        note=(
            "Marktech MT03-092 quadrant photodiode. Used in "
            "photovoltaic mode (no bias): common cathode → QPD_VREF "
            "(the TIAs' +IN mid-rail, so each junction sits at 0 V), "
            "each anode → AD8603 TIA on the qpd_module tile. 4 "
            "photodiode quadrants (A, B, C, D) with 200 µm dead-zone "
            "gaps between them. Sits behind the 1064 nm bandpass lens "
            "on the rigid qpd_module sensor tile."
        ),
    )
    fields.update(overrides)
    return design.add_chip(ref=ref, **fields)
